### ISSUE TITLE
Respect for requestPermissions?

### ISSUE THREAD

**Issue by mccolin** [djluck/azure-active-directory#2]
Is there a way to respect scope/permissions requests passed by the application via `options.requestPermissions`?

For instance, in this google login example, the "scope" URL argument is passed to the dialog, asking for additional permissions from the end user: https://github.com/meteor/meteor/blob/devel/packages/google/google_client.js#L29

Is this possible in azureAd? Does combining request scopes into a URL element -- as in the google example -- work for azure oauth login?

**Comment by djluck** [comment]
Hi mccolin,

Currently scopes aren't (knowingly) implemented by this package. The reason is that by default, when you register an application in azure ad they are assigned the "UserProfile.Read" scope and this is sufficient to get the user name and email address. You can see a list of scopes supported by azure ad/ office 365 here-

**Comment by djluck** [comment]
(Accidently submitted the comment)

https://msdn.microsoft.com/office/office365/HowTo/application-manifest

To further confuse the issue, it seems that you can statically assign permissions to an app.

This is something I will be reviewing the the future as I will be aiming to integrate this package with the office 365 APIs. I'm on holiday until the 17th of February so this may take a while.

I hope this sheds some light on why scope isnt currently implemented. I'll update this issue once I know what needs to be done. If you want to add scope passing before this time, feel free to make a pull request and I'll merge it as soon as I can.

James

**Comment by mccolin** [comment]
Thanks for the comments, James! I took a crack at adding the ability to pass scopes following the examples set forth by a third-party google lib, but the Azure Oauth dialogs don't seem to respect the `scope` URL parameter. I may be missing something configuration-wise, which I'll double-check when I have the time.

Have you worked with the app manifest file to specify permissions in the past? Documentation on the JSON schema is evading all of my best attempts at research and searching for it.

Cheers!

Colin

**Comment by mccolin** [comment]
For reference, the changes I'd prepared for the parameter are viewable in this commit: https://github.com/emmerge/azure-active-directory/commit/2f0dc9b5e6cbc0907068e738c7adf5a0173f103d

**Comment by djluck** [comment]
Hey mccolin, 

Apologies for dropping off the radar, it's been a hectic week. Your changes look good so it's curious that your report that scope isn't respected. What scopes did you try passing? 

I've worked very briefly with the app manifests, I didn't like what I saw. I believe you should only have to touch this if your app wishes to expose permissions to other azure ad apps but I may be wrong.

**Comment by qbalin** [comment]
Hi djluck, 

I'm working with mccolin and I'm very interested into using your package!
For that particular matter, it seems that there is no way to select specific permissions at authentication time: instead, you have to chose them on the AzureAd management page. I may be wrong, but this is what I understood from the AzureAd management UI and this post:

http://blogs.msdn.com/b/exchangedev/archive/2014/10/28/oauth2-in-action-with-the-release-of-office-365-calendar-contacts-and-mail.aspx

That said, I'm having a different issue. The AzureAd management account we have is linked to our company's 365 domain of course, and from the AzureAd management page, we can set permissions for our app. Now, when trying to OAuth with your package, in our application, with a company 365's address, we are able to connect, although we are never asked if we agree to grant any permission... Fine. But when trying to connect with a 365 email account from another domain (not the one of our company that is used for AzureAd management, then), I systematically get the 403 error Authorization_RequestDenied with the message "The specified credentials do no have sufficient privileges to make this request".

I do not know if this is the right place to ask this, but the microsoft documentation being rather unhelpful, I decided to ask you: have you seen this error before? Am I trying to use your package in a way it was not originally designed for?

Thanks!

**Comment by djluck** [comment]
@qbalin,

I think you're right about the first point- permissions can only be granted ahead of time and never requested by the application at run time.

Regarding your second point, I think that would make sense- your meteor app is only authorized to access your company's Azure AD tenant (a 'tenant' is what the documentations refers to as an installation or domain instance). When a user from another Azure AD tenant tries to log into your meteor app it fails, as this tenant has not registered with your meteor app.

What is slightly confusing however is the existence of the office 365 sandbox- this seems to be able to authenticate any office 365 user across multiple Azure AD tenants without them registering the app before hand. I think that perhaps Microsoft has a granted special access for this app perhaps because the documentation suggests that this is impossible.

**Comment by qbalin** [comment]
This domain limitation seems terrible to me, it would mean you cannot write an application using OAuth to offer a service for all 365 accounts (!!!) . I cannot believe Microsoft would have released such a poor interface; I will blame it on my incapacity to find the answer rather than the supposed lameness of this product for now :)

Well, thanks for your answer James, I am happy to have your thoughts on the subject.
I haven't asked Microsoft people yet, I think for now I'll try to access the necessary data without OAuth, by asking the users to provide us their password and username D: , although it is not the best security-wise.

**Comment by djluck** [comment]
I'm closing this issue now, thanks for all the assistance guys.
